# Generated by Django 5.2.4 on 2025-07-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('DEV', 'Creador de juegos')], default='USER', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDIDO', 'Suspended'), ('BANNED', 'Banned')], default='ACTIVE', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
