# Generated by Django 5.2.4 on 2025-07-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ninckname',
            new_name='nickname',
        ),
    ]
