# Generated by Django 5.2.4 on 2025-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0004_rename_ninckname_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.URLField(default='https://vanacco.com/wp-content/uploads/2022/01/Videogame-claves-1-1200x1200.jpg'),
        ),
    ]
