# Generated by Django 5.2.4 on 2025-07-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0005_alter_juego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
