# Generated by Django 5.2.4 on 2025-07-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamApp', '0006_user_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegobiblioteca',
            name='biblioteca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SteamApp.biblioteca'),
        ),
    ]
